/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package postest6;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fajarkh
 */
import java.sql.*;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
public class cari_buku extends javax.swing.JFrame{
private DefaultTableModel model;
public String open;
private Connection con = koneksi.getConnection();
private Statement stt;
private ResultSet rss;

int id,harga,confirm;
public String judul,penulis;
    /**
     * Creates new form cari_buku
     */
    public cari_buku () {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_keluar = new javax.swing.JButton();
        op = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        kol_jud = new javax.swing.JTextField();
        kol_hgr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        com_pen = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        tid = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        kol_cari = new javax.swing.JTextField();
        com_cari = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(java.awt.SystemColor.window);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        btn_keluar.setText("X");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        op.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        op.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op.setText("FORM DATA BUKU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_keluar))
            .addComponent(op, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_keluar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(op, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });

        kol_jud.setToolTipText("judul");
        kol_jud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kol_judKeyReleased(evt);
            }
        });

        kol_hgr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kol_hgrKeyReleased(evt);
            }
        });

        jLabel1.setText("Judul       :");

        jLabel2.setText("Penulis    :");

        com_pen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fajar KH", "Galalio", "Bung bud", "Misaki" }));

        jLabel3.setText("Harga     :");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        tid.setForeground(new java.awt.Color(255, 255, 255));
        tid.setText("   ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tid)
                        .addGap(30, 30, 30))
                    .addComponent(kol_jud)
                    .addComponent(kol_hgr)
                    .addComponent(com_pen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kol_jud, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(com_pen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kol_hgr, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(tid))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Judul", "Penulis", "Harga"
            }
        ));
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.setBackground(new java.awt.Color(0, 204, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DAFTAR BUKU");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
        );

        btn_tambah.setText("+ tambah");
        btn_tambah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_hapus.setText("- Hapus");
        btn_hapus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        kol_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kol_cariKeyReleased(evt);
            }
        });

        com_cari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "judul", "penulis", "harga" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ubah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus)
                        .addGap(18, 18, 18)
                        .addComponent(kol_cari)
                        .addGap(2, 2, 2)
                        .addComponent(com_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah)
                    .addComponent(btn_ubah)
                    .addComponent(btn_hapus)
                    .addComponent(kol_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(com_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void InitTable(){
        model = new DefaultTableModel();
        model.addColumn("JUDUL"); //Menambah kolom dengan nama JUDUL
        model.addColumn("PENULIS"); //Menambah kolom dengan nama PENULIS
        model.addColumn("HARGA"); //Menambah kolom dengan nama HARGA
        model.addColumn("ID"); //Menambah kolom dengan nama ID
        jTable1.setModel(model);
        jTable1.getColumn("ID").setPreferredWidth(0);
        jTable1.getColumn("ID").setMinWidth(0);
        jTable1.getColumn("ID").setWidth(0);
        jTable1.getColumn("ID").setMaxWidth(0);
 }
public void cekisi() { //fungsi untuk cek isi setiap inputan
    try{
   harga = Integer.parseInt(kol_hgr.getText());}
    catch (NumberFormatException e) {
               kol_hgr.setText("");
       }
     if (kol_jud.getText().length()==0){
       kol_jud.requestFocus();
       kol_jud.setBackground(Color.RED);
       kol_jud.setToolTipText("Tidak Boleh Kosong !"); 
       btn_simpan.setEnabled(false);}
       else {
       kol_jud.setBackground(Color.white);
       kol_jud.setToolTipText("judul"); 
       btn_simpan.setEnabled(true);
       if(jTable1.isFocusable()==false){
       btn_simpan.setEnabled(true);}
        }
} 
public void cekkeluar(){ //fungsi untuk cek jika ada penambahan / perubahan data 
if (kol_jud.getText().length()!=0){
    confirm = JOptionPane.showConfirmDialog(this, "simpan dulu datanya ?","konfirmasi",JOptionPane.YES_NO_CANCEL_OPTION);
    if(confirm==JOptionPane.YES_OPTION){
        if(btn_simpan.isEnabled()==true){
            btn_simpan.doClick();}
        else {btn_ubah.doClick();}
            setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
    if(confirm==JOptionPane.NO_OPTION){setDefaultCloseOperation(EXIT_ON_CLOSE);}
    if(confirm==JOptionPane.CANCEL_OPTION) {
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);}
}
else {setDefaultCloseOperation(EXIT_ON_CLOSE);} 
}
    private void TampilData(){ //method yg berfungsi untuk menampilkan data pada tabel dari database
        try{
            String sql = "SELECT * FROM buku"; //sql untuk menampilkan data dari tabel buku
            stt = con.createStatement(); //mulai statemen agar bisa 
            rss = stt.executeQuery(sql); //Yang menjalankan fungsi sql yang telah ditulis
            while(rss.next()){ // perulangan result set dari variable rss hingga tidak terpenuhi untuk perulangan
                //menampilkan data sesuai array :
                Object[] o = new Object[4];
                o[0] = rss.getString("judul"); //Data kolom judul dari tabel buku dimasukkan kedalam object o
                o[1] = rss.getString("penulis"); //Data kolom penulis dari tabel buku dimasukkan kedalam object o
                o[2] = rss.getInt("harga"); //Data kolom harga dari tabel buku dimasukkan kedalam object o
                o[3] = rss.getInt("id"); //Data kolom id dari tabel buku dimasukkan kedalam object o
                model.addRow(o); // Data-data tadi lalu di masukkan kedalam jTable1
                
            }
        }catch(SQLException e){
            System.out.println(e.getMessage()); //Menangkap kesalahan SQL jika terjadi
        }
        
    }
    private void ftambah(){ //Fungsi yang berfungsi untuk menambah data ke databases tabel buku 
        judul = kol_jud.getText();
        penulis = com_pen.getSelectedItem().toString();
        try{
            String sql = "INSERT INTO buku VALUES(NULL,'"+judul+"','"+penulis+"',"+harga+")"; 
            //Fungsi SQL yang digunakan untuk memasukan data yaitu Insert
            stt = con.createStatement();
            stt.executeUpdate(sql); //execute Update yang menjalankan querynya
            model.addRow(new Object[]{judul,penulis,harga});
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    private void fupdate(){ //Fungsi yang digunakkan untuk mengubah data atau mengupdate data
//        int baris = jTable1.getSelectedRow();
        String judul = kol_jud.getText(); //Mengambil judul yang dari jTextfield txtJudul
        String penulis = com_pen.getSelectedItem().toString();  //Mengambil penulis yang dari comboPenulis
        int ids = Integer.parseInt(tid.getText()); //Mengambil data ID yang dari jLabel tid
        try{
            String sql = "update buku set judul='"+judul+"', penulis='"+penulis+"', harga='"+harga+"'Where id='"+ids+"'";
            //query sql untuk mengupdate dimana id = ids, ids berisi id penulis
            stt = con.createStatement();
            stt.executeUpdate(sql); // yang menjalankan querynya
        }catch(SQLException e){
            System.out.println(e.getMessage()); //Menangkap kesalahan SQL jika terjadi
        }
    }
    
    private void fhapus(){ //Fungsi yang digunakkan untuk menghapus data dari tabel buku di databases
        String judul = kol_jud.getText();
        String penulis = com_pen.getSelectedItem().toString();
        int harga = Integer.parseInt(kol_hgr.getText());
        int ids = Integer.parseInt(tid.getText()); //Mengambil data ID yang dari jLabel tid
        try{
            String sql = "delete from buku where id='"+ids+"'";
            //SQL menghapus data berdasarkan id yang mana id=ids
            stt = con.createStatement();
            stt.executeUpdate(sql); //  yang menjalankan query sql
        }catch(SQLException e){
            System.out.println(e.getMessage()); //Menangkap kesalahan SQL jika terjadi
        }
        
        
    }
    
    private void fcari(){ //Fungsi yang digunakkan untuk mencari data dari tabel buku di databases
        String caridengan = com_cari.getSelectedItem().toString();
        //String caridengan merupakan string yang menyimpan data pilihan dari jComboBox 
        try{
            String sql = "select * from buku where "+caridengan+" like '%"+kol_cari.getText()+"%'";
            //Perinth sql menampilkan data berdasarkan isi variabel caridata (jenis pencarian) dengan keyword sesuai isi kol_cari
            stt = con.createStatement();
            rss = stt.executeQuery(sql);//eksekusi query
            ResultSet rss=stt.executeQuery(sql);
            while(rss.next()){// perulangan result set dari variable rss hingga tidak terpenuhi untuk perulangan
                //menampilkan data sesuai array :
                Object[] o=new Object[4];
                o[0]=rss.getString("judul");
                o[1]=rss.getString("penulis");
                o[2]=rss.getInt("harga");
                o[3]=rss.getInt("id");
                model.addRow(o);
                //data yang didapat(dicari) dimasukkan kedalam jTable
            }
            
        }catch(SQLException e){System.out.println(e.getMessage());} //Menangkap kesalahan jika terjadi
    }
    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
cekkeluar();
if(confirm==JOptionPane.CANCEL_OPTION) {
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE); }
else {System.exit(0);}
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        btn_ubah.setEnabled(true);
        btn_hapus.setEnabled(true);
        int baris = jTable1.getSelectedRow();
        String judul=jTable1.getValueAt(baris, 0).toString();
        String penulis=jTable1.getValueAt(baris, 1).toString();
        String harga=jTable1.getValueAt(baris, 2).toString();
        String ids = jTable1.getValueAt(baris, 3).toString();
        
        tid.setText(ids);
        kol_jud.setText(judul);
        com_pen.setSelectedItem(penulis);
        kol_hgr.setText(harga);
    }//GEN-LAST:event_jTable1MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
InitTable();
TampilData();
    }//GEN-LAST:event_formComponentShown

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
ftambah();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        TampilData();
        kol_jud.setText("");
        kol_hgr.setText("");
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
 model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        fupdate();
        TampilData();
        kol_jud.setText("");
        kol_hgr.setText("");
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        int baris = jTable1.getSelectedRow();
        String judul=jTable1.getValueAt(baris, 0).toString();
        String penulis=jTable1.getValueAt(baris, 1).toString();
        String harga=jTable1.getValueAt(baris, 2).toString();
        String ids = jTable1.getValueAt(baris, 3).toString();
        
        tid.setText(ids);
        kol_jud.setText(judul);
        com_pen.setSelectedItem(penulis);
        kol_hgr.setText(harga);
    }//GEN-LAST:event_jTable1KeyReleased

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        fhapus();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        TampilData();
        kol_jud.setText("");
        kol_hgr.setText("");
        btn_ubah.setEnabled(false);
        btn_hapus.setEnabled(false);
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btn_ubah.setEnabled(false);
        btn_hapus.setEnabled(false);
        btn_simpan.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void kol_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kol_cariKeyReleased
model.getDataVector().removeAllElements();//kosongkan tampilan tabel
        model.fireTableDataChanged();//atur ke bentuk semula baris dan kolom tabel
        fcari(); // lalukan fungsi fcari
    }//GEN-LAST:event_kol_cariKeyReleased

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
btn_simpan.setEnabled(true);
kol_jud.requestFocus();
jTable1.clearSelection(); //hilangkan penanda pada tabel
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
btn_simpan.setEnabled(false);

    }//GEN-LAST:event_jTable1FocusGained

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
    }//GEN-LAST:event_jPanel2MouseEntered

    private void kol_judKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kol_judKeyReleased
cekisi();
    }//GEN-LAST:event_kol_judKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
cekkeluar();
    }//GEN-LAST:event_formWindowClosing

    private void kol_hgrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kol_hgrKeyReleased
cekisi();
    }//GEN-LAST:event_kol_hgrKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cari_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cari_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cari_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cari_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cari_buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox com_cari;
    private javax.swing.JComboBox com_pen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kol_cari;
    private javax.swing.JTextField kol_hgr;
    private javax.swing.JTextField kol_jud;
    private javax.swing.JLabel op;
    private javax.swing.JLabel tid;
    // End of variables declaration//GEN-END:variables
}
